---
- id: "1638343285502"
  alias: Turn on music room lights
  description: ""
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.music_room_motion
      light_target:
        device_id: eb52fbe94800bb61995e16e63f850872
- id: "1638369663538"
  alias: Turn on utility room lights
  description: ""
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      light_target:
        area_id: utility_room
      motion_entity: binary_sensor.utility_room_motion
