- platform: qnap
  host: !secret qnap_host
  username: !secret qnap_username
  password: !secret qnap_password
  monitored_conditions:
    - status
    - cpu_usage
    - system_temp
    - cpu_temp
    - memory_percent_used
    - memory_free
    - memory_used
    - network_link_status
    - network_tx
    - network_rx
    - drive_smart_status
    - drive_temp
    - volume_size_free
    - volume_size_used
    - volume_percentage_used
